spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university-cms
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/university-cms
    user: postgres
    password: password
    locations: db/migration
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/images/
server:
  port: 8081
aws:
  s3:
    accessKeyId: password
    secretAccessKey: password
    bucket-name: bucket_name
