spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university-cms
    username: postgres
    password: 987654321Lord
  flyway:
    url: jdbc:postgresql://localhost:5432/university-cms
    user: postgres
    password: 987654321Lord
    locations: db/migration
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/images/
server:
  port: 8081
app:
  image:
    storage:
      userProfileDirectory: ./user-profile-images/
      applicationImagesDirectory: ./application-images/
